**Suppliers**

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from pathlib import Path

In [12]:
file_path = Path.cwd().parent.parent/"Data"/"Cleaned"/"Suppliers.csv"
df = pd.read_csv(file_path)
df

   Supplier_ID Supplier_Name Region  Lead_Time_Days  Reliability_Score
0         S100    Supplier 1  South              21              55.46
1         S101    Supplier 2  South              27              94.38
2         S102    Supplier 3   East               7              61.56
3         S103    Supplier 4   East              24              89.58
4         S104    Supplier 5   West              26              82.19
..         ...           ...    ...             ...                ...
95        S195   Supplier 96   East              23              83.73
96        S196   Supplier 97   East              20              80.50
97        S197   Supplier 98  North               6              55.98
98        S198   Supplier 99   West              19              10.00
99        S199  Supplier 100  South               6              56.82

[100 rows x 5 columns]

In [13]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Supplier_ID        100 non-null    object
 1   Supplier_Name      100 non-null    object
 2   Region             100 non-null    object
 3   Lead_Time_Days     100 non-null    int64
 4   Reliability_Score  100 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB

In [14]:
# Adding Reliability Category for Analysis
df["Reliability_Category"] = pd.cut(
    df["Reliability_Score"],
    bins=[0, 60, 80, 100],
    labels=["Low", "Medium", "High"]
)

In [15]:
# Adding Delivery Category for Analysis
def delivery_category(x):
    if x <= 7:
        return "Fast"
    elif x <= 14:
        return "Medium"
    elif x<=21:
        return "Slow"
    else :
        return "Poor"

df["Lead_Time_Category"] = (
    df["Lead_Time_Days"].apply(delivery_category)
)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Supplier_ID           100 non-null    object
 1   Supplier_Name         100 non-null    object
 2   Region                100 non-null    object
 3   Lead_Time_Days        100 non-null    int64
 4   Reliability_Score     100 non-null    float64
 5   Reliability_Category  100 non-null    category
 6   Lead_Time_Category    100 non-null    object
dtypes: category(1), float64(1), int64(1), object(4)
memory usage: 5.0+ KB

In [17]:
# Region wise Suppliers Information
result = df.groupby("Region").agg(
    Total_Suppliers = ("Supplier_ID", "count"),
    Avg_Time_Delay = ("Lead_Time_Days", "mean"),
    Avg_Reliability_Score = ("Reliability_Score", "mean")
).round(2).reset_index().sort_values(by="Avg_Reliability_Score", ascending=False)
result

  Region  Total_Suppliers  Avg_Time_Delay  Avg_Reliability_Score
0   East               24           16.62                  64.05
2  South               29           14.52                  61.26
1  North               24           17.12                  55.31
3   West               23           17.52                  49.03

In [ ]:
result = df.groupby("Lead_Time_Category").agg(
    Total_Suppliers = ("Supplier_ID", "count")
)
result

                    Total_Suppliers
Lead_Time_Category
Fast                             22
Medium                           22
Poor                             33
Slow                             23

In [19]:
result = df.groupby("Reliability_Category").agg(
    Total_Suppliers = ("Supplier_ID", "count")
)
result

C:\Users\hp\AppData\Local\Temp\ipykernel_4880\2240075537.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby("Reliability_Category").agg(

                      Total_Suppliers
Reliability_Category
Low                                40
Medium                             33
High                               27

In [20]:
df.to_csv("../../Data/Processed/Suppliers.csv", index=False)