**Warehouses**

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from pathlib import Path

In [40]:
file_path = Path.cwd().parent.parent/"Data"/"Cleaned"/"Warehouses.csv"
df = pd.read_csv(file_path)
df

   Warehouse_ID Warehouse_Name Region  Capacity  Operating_Cost
0          W100    Warehouse 1  South     78268       131401.36
1          W101    Warehouse 2   West     53567       409621.09
2          W102    Warehouse 3  South     52613       200386.72
3          W103    Warehouse 4   West     55891       378891.66
4          W104    Warehouse 5   West     31243       239004.95
5          W105    Warehouse 6   West     51993       310261.89
6          W106    Warehouse 7   East     65026       424675.30
7          W107    Warehouse 8  South     58600       411874.50
8          W108    Warehouse 9  North     49512       439890.43
9          W109   Warehouse 10  North     62620        76827.80
10         W110   Warehouse 11  North     27089       361422.75
11         W111   Warehouse 12  North     42230       112994.32
12         W112   Warehouse 13   West     28983       237118.36
13         W113   Warehouse 14  South     16921       296864.79
14         W114   Warehouse 15  South     48804       231232.77
15         W115   Warehouse 16   East     77699       283825.25
16         W116   Warehouse 17  South     47619       498436.84
17         W117   Warehouse 18  South     17877       110847.79
18         W118   Warehouse 19  South     11871       353955.22
19         W119   Warehouse 20   East     12496       228200.43

In [41]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Warehouse_ID    20 non-null     object
 1   Warehouse_Name  20 non-null     object
 2   Region          20 non-null     object
 3   Capacity        20 non-null     int64
 4   Operating_Cost  20 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 932.0+ bytes

In [42]:
# Adding Category according to Capacity
def capacity_category(x):
    if x < 25000:
        return "Low"
    elif x < 50000:
        return "Medium"
    else:
        return "High"
df["Capacity_Category"] = df["Capacity"].apply(capacity_category)
df

,Warehouse_ID,Warehouse_Name,Region,Capacity,Operating_Cost,Capacity_Category
0,W100,Warehouse 1,South,78268,131401.36,High
1,W101,Warehouse 2,West,53567,409621.09,High
2,W102,Warehouse 3,South,52613,200386.72,High
3,W103,Warehouse 4,West,55891,378891.66,High
4,W104,Warehouse 5,West,31243,239004.95,Medium
5,W105,Warehouse 6,West,51993,310261.89,High
6,W106,Warehouse 7,East,65026,424675.30,High
7,W107,Warehouse 8,South,58600,411874.50,High
8,W108,Warehouse 9,North,49512,439890.43,Medium
9,W109,Warehouse 10,North,62620,76827.80,High
10,W110,Warehouse 11,North,27089,361422.75,Medium
11,W111,Warehouse 12,North,42230,112994.32,Medium
12,W112,Warehouse 13,West,28983,237118.36,Medium
13,W113,Warehouse 14,South,16921,296864.79,Low
14,W114,Warehouse 15,South,48804,231232.77,Medium
15,W115,Warehouse 16,East,77699,283825.25,High
16,W116,Warehouse 17,South,47619,498436.84,Medium
17,W117,Warehouse 18,South,17877,110847.79,Low
18,W118,Warehouse 19,South,11871,353955.22,Low
19,W119,Warehouse 20,East,12496,228200.43,Low

In [43]:
# Adding Category according to Operating Cost
def operating_cost_category(x):
    if x < 150000:
        return "Low"
    elif x < 250000:
        return "Medium"
    else:
        return "High"
df["Operating_Cost_Category"] = df["Operating_Cost"].apply(operating_cost_category)
df

,Warehouse_ID,Warehouse_Name,Region,Capacity,Operating_Cost,Capacity_Category,Operating_Cost_Category
0,W100,Warehouse 1,South,78268,131401.36,High,Low
1,W101,Warehouse 2,West,53567,409621.09,High,High
2,W102,Warehouse 3,South,52613,200386.72,High,Medium
3,W103,Warehouse 4,West,55891,378891.66,High,High
4,W104,Warehouse 5,West,31243,239004.95,Medium,Medium
5,W105,Warehouse 6,West,51993,310261.89,High,High
6,W106,Warehouse 7,East,65026,424675.30,High,High
7,W107,Warehouse 8,South,58600,411874.50,High,High
8,W108,Warehouse 9,North,49512,439890.43,Medium,High
9,W109,Warehouse 10,North,62620,76827.80,High,Low
10,W110,Warehouse 11,North,27089,361422.75,Medium,High
11,W111,Warehouse 12,North,42230,112994.32,Medium,Low
12,W112,Warehouse 13,West,28983,237118.36,Medium,Medium
13,W113,Warehouse 14,South,16921,296864.79,Low,High
14,W114,Warehouse 15,South,48804,231232.77,Medium,Medium
15,W115,Warehouse 16,East,77699,283825.25,High,High
16,W116,Warehouse 17,South,47619,498436.84,Medium,High
17,W117,Warehouse 18,South,17877,110847.79,Low,Low
18,W118,Warehouse 19,South,11871,353955.22,Low,High
19,W119,Warehouse 20,East,12496,228200.43,Low,Medium

In [44]:
# Warehouse having Low Capacity and High Operating Cost
df.loc[
    (df["Operating_Cost_Category"]=="High") &
    (df["Capacity_Category"]=="Low")
]

,Warehouse_ID,Warehouse_Name,Region,Capacity,Operating_Cost,Capacity_Category,Operating_Cost_Category
13,W113,Warehouse 14,South,16921,296864.79,Low,High
18,W118,Warehouse 19,South,11871,353955.22,Low,High

In [45]:
df.to_csv("../../Data/Processed/Warehouses.csv", index=False)