**Orders**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from pathlib import Path

In [2]:
file_path = Path.cwd().parent.parent/"Data"/"Cleaned"/"Orders.csv"
df = pd.read_csv(file_path)
df

,Order_ID,Order_Date,Product_ID,Warehouse_ID,Customer_ID,Quantity,Discount,Order_Status,Revenue
0,ORD1000000,2025-12-01,P1951,W115,C16553,4.0,0.0,Returned,1525.48
1,ORD1000001,2025-01-05,P1277,W113,C12342,4.0,10.0,Delivered,857.05
2,ORD1000002,2025-06-06,P1761,W108,C18945,6.0,15.0,Delivered,2500.79
3,ORD1000003,2025-04-29,P1137,W100,C12526,7.0,0.0,Delivered,2697.45
4,ORD1000004,2025-03-24,P1613,W101,C12314,5.0,15.0,Returned,2871.17
...,...,...,...,...,...,...,...,...,...
500008,ORD1500008,2025-10-25,P1445,W115,C14939,5.0,5.0,Delivered,1629.96
500009,ORD1500009,2025-07-14,P1284,W111,C12628,6.0,20.0,Delivered,407.04
500010,ORD1500010,2025-11-04,P1867,W107,C13166,2.0,15.0,Delivered,269.72
500011,ORD1500011,2025-09-05,P1493,W100,C13639,4.0,10.0,Cancelled,2183.72
500012,ORD1500012,2025-03-25,P1053,W100,C17158,4.0,0.0,Delivered,313.04

In [3]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500013 entries, 0 to 500012
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Order_ID      500013 non-null  object
 1   Order_Date    497513 non-null  object
 2   Product_ID    500013 non-null  object
 3   Warehouse_ID  500013 non-null  object
 4   Customer_ID   494325 non-null  object
 5   Quantity      499987 non-null  float64
 6   Discount      500013 non-null  float64
 7   Order_Status  494402 non-null  object
 8   Revenue       499996 non-null  float64
dtypes: float64(3), object(6)
memory usage: 34.3+ MB

In [4]:
df["Month"] = pd.to_datetime(df["Order_Date"]).dt.month
df

,Order_ID,Order_Date,Product_ID,Warehouse_ID,Customer_ID,Quantity,Discount,Order_Status,Revenue,Month
0,ORD1000000,2025-12-01,P1951,W115,C16553,4.0,0.0,Returned,1525.48,12.0
1,ORD1000001,2025-01-05,P1277,W113,C12342,4.0,10.0,Delivered,857.05,1.0
2,ORD1000002,2025-06-06,P1761,W108,C18945,6.0,15.0,Delivered,2500.79,6.0
3,ORD1000003,2025-04-29,P1137,W100,C12526,7.0,0.0,Delivered,2697.45,4.0
4,ORD1000004,2025-03-24,P1613,W101,C12314,5.0,15.0,Returned,2871.17,3.0
...,...,...,...,...,...,...,...,...,...,...
500008,ORD1500008,2025-10-25,P1445,W115,C14939,5.0,5.0,Delivered,1629.96,10.0
500009,ORD1500009,2025-07-14,P1284,W111,C12628,6.0,20.0,Delivered,407.04,7.0
500010,ORD1500010,2025-11-04,P1867,W107,C13166,2.0,15.0,Delivered,269.72,11.0
500011,ORD1500011,2025-09-05,P1493,W100,C13639,4.0,10.0,Cancelled,2183.72,9.0
500012,ORD1500012,2025-03-25,P1053,W100,C17158,4.0,0.0,Delivered,313.04,3.0

In [5]:
# Total Orders
total_orders = df.shape[0]
total_orders

500013

In [6]:
# Average Order value
average_order_value = df["Revenue"].mean()
average_order_value.round(2)

np.float64(1488.89)

In [7]:
df.groupby("Order_Status").agg(
    Total_Orders = ("Order_ID", "count"),
    Total_Revenue = ("Revenue", "sum"),
    Average_Order_Value = ("Revenue", "mean")
).round(2).sort_values(by="Total_Revenue", ascending=False)

              Total_Orders  Total_Revenue  Average_Order_Value
Order_Status
Delivered           246599   3.662805e+08              1485.39
Cancelled            82529   1.236432e+08              1498.18
Returned             82877   1.235043e+08              1490.25
Processing           82397   1.227389e+08              1489.68

In [8]:
df.groupby("Customer_ID").agg(
    Total_Orders = ("Order_ID", "count"),
    Total_Revenue = ("Revenue", "sum"),
    Average_Order_Value = ("Revenue", "mean")
).round(2).sort_values(by="Total_Revenue", ascending=False).head(10)

             Total_Orders  Total_Revenue  Average_Order_Value
Customer_ID
C17625                 79      146456.67              1853.88
C11184                 69      143637.36              2081.70
C18724                 74      141114.38              1906.95
C13134                 68      138655.27              2039.05
C19295                 62      137603.13              2219.41
C19127                 67      136185.15              2032.61
C11072                 67      135747.61              2026.08
C17819                 71      134443.00              1893.56
C15506                 63      133725.46              2122.63
C10891                 67      133312.65              1989.74

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500013 entries, 0 to 500012
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Order_ID      500013 non-null  object
 1   Order_Date    497513 non-null  object
 2   Product_ID    500013 non-null  object
 3   Warehouse_ID  500013 non-null  object
 4   Customer_ID   494325 non-null  object
 5   Quantity      499987 non-null  float64
 6   Discount      500013 non-null  float64
 7   Order_Status  494402 non-null  object
 8   Revenue       499996 non-null  float64
 9   Month         497513 non-null  float64
dtypes: float64(4), object(6)
memory usage: 38.1+ MB

In [10]:
df.to_csv("../../Data/Processed/Orders.csv", index=False)