**Purchases**

In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from pathlib import Path

In [39]:
file_path = Path.cwd().parent.parent/"Data"/"Cleaned"/"Purchases.csv"
df = pd.read_csv(file_path)
df

,Purchase_ID,Supplier_ID,Product_ID,Warehouse_ID,Purchase_Date,Quantity,Unit_Cost,Expected_Date,Actual_Date
0,PUR1000000,S105,P1063,W107,2025-05-01,691.0,514.16,2025-05-12,2025-05-17
1,PUR1000001,S184,P1355,W107,2025-01-23,1946.0,349.72,2025-01-25,2025-02-06
2,PUR1000002,S155,P1180,W114,2025-06-05,658.0,206.50,2025-07-04,2025-07-04
3,PUR1000003,S101,P1598,W116,2025-06-11,80.0,108.78,2025-07-08,2025-07-10
4,PUR1000004,S121,P1083,W112,2025-07-18,1082.0,121.36,2025-08-08,2025-08-06
...,...,...,...,...,...,...,...,...,...
74998,PUR1074998,S116,P1098,W114,2025-08-17,1128.0,257.11,2025-09-03,2025-09-02
74999,PUR1074999,S148,P1088,W119,2025-06-27,2533.0,754.60,2025-07-25,2025-07-28
75000,PUR1075000,S147,P1438,W109,2025-03-30,1833.0,102.57,2025-04-20,2025-04-18
75001,PUR1075001,S131,P1216,W108,2025-07-25,2032.0,90.67,2025-08-06,2025-08-09
75002,PUR1075002,S142,P1963,W103,2025-03-04,1098.0,445.72,2025-04-03,2025-04-03

In [40]:
# Converting to date data type
cols = ["Purchase_Date", "Expected_Date", "Actual_Date"]
for col in cols:
    df[col] = pd.to_datetime(df[col], format="%Y-%m-%d", errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75003 entries, 0 to 75002
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Purchase_ID    75003 non-null  object
 1   Supplier_ID    74984 non-null  object
 2   Product_ID     74983 non-null  object
 3   Warehouse_ID   75002 non-null  object
 4   Purchase_Date  74628 non-null  datetime64[ns]
 5   Quantity       74628 non-null  float64
 6   Unit_Cost      74628 non-null  float64
 7   Expected_Date  74628 non-null  datetime64[ns]
 8   Actual_Date    74628 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(2), object(4)
memory usage: 5.2+ MB

In [41]:
df

,Purchase_ID,Supplier_ID,Product_ID,Warehouse_ID,Purchase_Date,Quantity,Unit_Cost,Expected_Date,Actual_Date
0,PUR1000000,S105,P1063,W107,2025-05-01,691.0,514.16,2025-05-12,2025-05-17
1,PUR1000001,S184,P1355,W107,2025-01-23,1946.0,349.72,2025-01-25,2025-02-06
2,PUR1000002,S155,P1180,W114,2025-06-05,658.0,206.50,2025-07-04,2025-07-04
3,PUR1000003,S101,P1598,W116,2025-06-11,80.0,108.78,2025-07-08,2025-07-10
4,PUR1000004,S121,P1083,W112,2025-07-18,1082.0,121.36,2025-08-08,2025-08-06
...,...,...,...,...,...,...,...,...,...
74998,PUR1074998,S116,P1098,W114,2025-08-17,1128.0,257.11,2025-09-03,2025-09-02
74999,PUR1074999,S148,P1088,W119,2025-06-27,2533.0,754.60,2025-07-25,2025-07-28
75000,PUR1075000,S147,P1438,W109,2025-03-30,1833.0,102.57,2025-04-20,2025-04-18
75001,PUR1075001,S131,P1216,W108,2025-07-25,2032.0,90.67,2025-08-06,2025-08-09
75002,PUR1075002,S142,P1963,W103,2025-03-04,1098.0,445.72,2025-04-03,2025-04-03

In [42]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75003 entries, 0 to 75002
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Purchase_ID    75003 non-null  object
 1   Supplier_ID    74984 non-null  object
 2   Product_ID     74983 non-null  object
 3   Warehouse_ID   75002 non-null  object
 4   Purchase_Date  74628 non-null  datetime64[ns]
 5   Quantity       74628 non-null  float64
 6   Unit_Cost      74628 non-null  float64
 7   Expected_Date  74628 non-null  datetime64[ns]
 8   Actual_Date    74628 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(2), object(4)
memory usage: 5.2+ MB

In [43]:
# Adding Total Bill column
df["Total_Bill"] = (df["Quantity"] * df["Unit_Cost"]).round(2)

In [44]:
delivery_days = (df["Actual_Date"] - df["Purchase_Date"]).dt.days
df["Delivery_Days"] = delivery_days

In [45]:
def delivery_status(row):
    if row["Actual_Date"] < row["Expected_Date"]:
        return "Early Delivery"
    elif row["Actual_Date"] == row["Expected_Date"]:
        return "On Time"
    elif row["Actual_Date"] > row["Expected_Date"]:
        return "Late Delivery"
    else:
        return np.nan
df["Delivery_Status"] = df.apply(delivery_status, axis=1)
df

,Purchase_ID,Supplier_ID,Product_ID,Warehouse_ID,Purchase_Date,Quantity,Unit_Cost,Expected_Date,Actual_Date,Total_Bill,Delivery_Days,Delivery_Status
0,PUR1000000,S105,P1063,W107,2025-05-01,691.0,514.16,2025-05-12,2025-05-17,355284.56,16.0,Late Delivery
1,PUR1000001,S184,P1355,W107,2025-01-23,1946.0,349.72,2025-01-25,2025-02-06,680555.12,14.0,Late Delivery
2,PUR1000002,S155,P1180,W114,2025-06-05,658.0,206.50,2025-07-04,2025-07-04,135877.00,29.0,On Time
3,PUR1000003,S101,P1598,W116,2025-06-11,80.0,108.78,2025-07-08,2025-07-10,8702.40,29.0,Late Delivery
4,PUR1000004,S121,P1083,W112,2025-07-18,1082.0,121.36,2025-08-08,2025-08-06,131311.52,19.0,Early Delivery
...,...,...,...,...,...,...,...,...,...,...,...,...
74998,PUR1074998,S116,P1098,W114,2025-08-17,1128.0,257.11,2025-09-03,2025-09-02,290020.08,16.0,Early Delivery
74999,PUR1074999,S148,P1088,W119,2025-06-27,2533.0,754.60,2025-07-25,2025-07-28,1911401.80,31.0,Late Delivery
75000,PUR1075000,S147,P1438,W109,2025-03-30,1833.0,102.57,2025-04-20,2025-04-18,188010.81,19.0,Early Delivery
75001,PUR1075001,S131,P1216,W108,2025-07-25,2032.0,90.67,2025-08-06,2025-08-09,184241.44,15.0,Late Delivery
75002,PUR1075002,S142,P1963,W103,2025-03-04,1098.0,445.72,2025-04-03,2025-04-03,489400.56,30.0,On Time

In [46]:
df.to_csv("../../Data/Processed/Purchases.csv", index=False)